version: "3"
services:
  golang:
    image: golang:1.19-alpine
    container_name: lucysplains_go
    tty: true
    volumes:
      - ../:/var/local/lucysplains
    environment:
      OPEN_AI_KEY: "YOUR_API_KEY_FROM_OPENAI_HERE"
    working_dir: /var/local/lucysplains
